### ISSUE TITLE
"Black" screen in debugger

### ISSUE THREAD

**Issue by Ace-Lightning** [binji/binjgb#11]
Hi,
I have a trouble: when I launch binjgb-debugger nothing happens. There is music from Game, but screen is black (gray). 
When I press some keys there are some responds, but screen stays in black.

**Comment by Ace-Lightning** [comment]
So, I discovered when I press F11 to full screen the elements of debugger show.

**Comment by binji** [comment]
Interesting, I'll take a look.

**Comment by binji** [comment]
I tried on Windows and found the same issue.. strange because it didn't happen on Linux. Should be fixed now though. Thanks for trying it out!
