### ISSUE TITLE
Force DMG mode?

### ISSUE THREAD

**Issue by gregkatz** [binji/binjgb#18]
I couldn't find it documented, so I thought I'd ask: Is there any way to force DMG mode? I'm trying to use your emulator's tracing to see where my emulator diverges, but I'm not currently aiming for CGB support.

**Comment by binji** [comment]
There wasn't, but I just added one. :-)

You can pass `--force-dmg` to any of the executables and they won't load as CGB.

**Comment by gregkatz** [comment]
Thanks! I really appreciate it!
