### ISSUE TITLE
Run Boot Rom

### ISSUE THREAD

**Issue by hevey** [binji/binjgb#24]
Is there a way to run the DMG Boot Rom? I am developing an emulator on a Mac and the debugger looks great but I can't find a way to run the boot rom to compare my own emulator with.

**Comment by binji** [comment]
Sorry, I never added this feature. There a bunch of other emulators that do this though, you should be able to find one that works for you.

**Comment by hevey** [comment]
Cheers for the reply, I have others to use, was more curious as the visual debugger looks fantastic.
