### ISSUE TITLE
Joypad interrupt does not fire

### ISSUE THREAD

**Issue by pinobatch** [binji/binjgb#25]
_The Lawnmower Man_ for Game Boy reportedly [will not start](https://github.com/mgba-emu/mgba/issues/388) unless joypad interrupts are implemented.

To reproduce:

1. Download and unzip the attached test ROM "Telling LYs?" [tellinglys-for-binjgb.zip](https://github.com/binji/binjgb/files/4394378/tellinglys-for-binjgb.zip)
2. In binjgb, load and run the ROM
3. Press any button

Observed behavior:

Title screen does not disappear; the test cannot progress.

Expected behavior:

Display advances from title screen to conversation, and pressing other buttons advances the conversation.

(If you do issue joypad interrupts, but you don't vary the LY when they're issued, you'll get a different error message.)

**Comment by binji** [comment]
Thanks for the bug report! Should be fixed now.

**Comment by pinobatch** [comment]
Pass!
