### ISSUE TITLE
Scaling is uneven

### ISSUE THREAD

**Issue by pinobatch** [binji/binjgb#26]
The scaling is uneven, possibly because of the 1-pixel black border around the screen.

Steps to reproduce

1. Download gb240p.gb from [240p-test-mini v0.20](https://github.com/pinobatch/240p-test-mini/releases/tag/v0.20)
2. In binjgb, load and run gb240p.gb
3. On the second page of the menu, open Full screen stripes
4. Set magnification to 2x or 3x
5. Press X (bound to the A Button) several times to rotate the stripes

Observed behavior:

One stripe about 1/4th of the way from each side is one pixel narrower than the others.

Expected behavior:

All stripes have the same thickness.

**Comment by binji** [comment]
I think this should be fixed now, please re-open if not.

**Comment by pinobatch** [comment]
Took a few force reloads (Ctrl+Shift+R) to get the `box-sizing: content-box;` rule to propagate to <https://binji.github.io/binjgb/>, but it's fixed now.
