### ISSUE TITLE
Feature request: add a .sav import/export feature

### ISSUE THREAD

**Issue by cyberic99** [binji/binjgb#39]
I tried by different means to download the 'db' indexedDB data.
I was able to see the base64-encoded screenshot, but the 'extram' blob, despite having a size of 131072, was always empty.

Is there anything special to do in order to import or export .sav files?

thx

**Comment by binji** [comment]
Sorry for delay. Were you able to get this working? One thing to mention about importing/exporting .sav files is that they may not be compatible with other emulators.

**Comment by cyberic99** [comment]
Hello. No I couldn't get it working.
The aim is to import or export .sav containing LSDj songs, so compatibility with other emulators (and even flash carts) would be much appreciated.

**Comment by cyberic99** [comment]
Hello @binji can you give me a hint about how I could get a .sav file from the browser storage?

is the save related to the 'extRam' object?

Thanks

**Comment by binji** [comment]
Finally added this feature, sorry it took so long. See https://github.com/binji/binjgb/commit/ba152e9505d942b130d426befe28c60a6a75d557

Let me know if that works for you!
