### ISSUE TITLE
Scanlines with the BG/Window disabled don't clear old sprite pixels

### ISSUE THREAD

**Issue by tbsp** [binji/binjgb#40]
If a game has the BG and window disabled, but objects enabled, pixels from sprites linger once drawn until overwritten by sprites once again.

**Comment by tbsp** [comment]
[sprite_bug.zip](https://github.com/binji/binjgb/files/6863365/sprite_bug.zip)
This ROM includes a simple sprite to move around with the BG/Win disabled to demonstrate the bug.

**Comment by binji** [comment]
Thanks! Should be fixed in https://github.com/binji/binjgb/commit/408bee8ca1fdc83c15422c323a9e27bf8d35bfcd.
