### ISSUE TITLE
Fatass Tracker doesn't work

### ISSUE THREAD

**Issue by dag7dev** [binji/binjgb#49]
## Description
When Fatass Tracker tries to load, it doesn't work.
It says "File size too small" and freezes.
However, with other emulators, that rom perfectly works!

## Steps
1. Go here: https://hh.gbdev.io/game/fatass
2. Open web console
3. It says "File size too small (required 524288, got 425984)"
4. (optional) to test yourself, download the rom, download mgba. It works.

Could we do something to fix this behaviour?

**Comment by avivace** [comment]
Direct link to the ROM download: https://hh3.gbdev.io/entries/fatass/fatass.gb

**Comment by dag7dev** [comment]
It seems similar, may be the same issue? I am not sure...
In case I'll migrate everything there!

**Comment by binji** [comment]
Should be fixed in 7275f65, please reopen if not.

**Comment by avivace** [comment]
Thanks binji! Looks like those kind of entries work now
